# Generated by Django 5.1.5 on 2025-07-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='created_at',
        ),
    ]
