# Generated by Django 5.1.5 on 2025-08-05 12:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_fooditem_options_remove_fooditem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
